export interface BranchSettings {
    id: number;
    branchId: number;
    updateTime: Date;
    orderConfirmGift: boolean;
    orderConfirmPriceLessInPrice: boolean;
    purchaseCollectDefaultPurchaser: number;
    autoAuditing: boolean;
    hideSaleNum: boolean;
    hidePurchaseZero: boolean;
    returnOrderInStoreForCheck: boolean;
    accountPeriodLimitOrder: number;
    isCustomMessageSignature: boolean;
    goodsCategory: boolean;
    goodsDetailDisplayInventory: boolean;
    goodsListRandom: boolean;
    canvass: boolean;
    addThirdPartyId: boolean;
    isShowGrossProfit: boolean;
    isAccountVialid: boolean;
    groupCheckedAllOrder: boolean;
    isCustomerDetails: boolean;
    branchSite: boolean | null;
    singleStroe: boolean;
    customerNeedApprove: boolean | null;
    isRepeatGoodsSn: boolean;
    isHideGoodsEvaluate: boolean;
    isThird: boolean;
    customerManageId: number;
    limitOrderForNoStock: boolean | null;
    isDefaultStore: boolean | null;
    limitWebOrderForNoVirtualStock: number | null;
    financeAudit: boolean | null;
    onlyMallOrder: boolean | null;
    branchIdOfHideMoney: string;
    inPriceHigherThanPrice: boolean | null;
    orderRequiredMemo: boolean | null;
    modifyGoodsUnit: boolean | null;
    isShowInvalidPurchaser: boolean | null;
    isShowGoodsSaleCount: boolean | null;
    orderConfirmReturnDirectDelivery: boolean | null;
    purchaseCollectByStore: boolean | null;
    storeOrderUsePrice: boolean | null;
    orderDefaultTaxRate: number | null;
    purchaseDefaultTaxRate: number | null;
    specifySupplier: boolean;
    showVirtualSales: boolean;
    orderToDistribution: boolean | null;
    storeOrderSpecifySalesman: boolean;
    storeOrderSpicifyInventory: boolean;
    purchaseByOwin: boolean;
    exportByAdmin: boolean;
}
