export interface Customer {
    id: number;
    branchId: number;
    name: string;
    shortName: string;
    type: string;
    status: string;
    employeesNum: string;
    province: string;
    city: string;
    area: string;
    address: string;
    postCode: string;
    telphone: string;
    fax: string;
    website: string;
    registerMethod: string;
    userId: number;
    addTime: Date;
    updateTime: Date;
    level: number;
    salesId: number;
    serviceId: number;
    statementManId: number;
    orderDiscount: number;
    orderMemo: string;
    orderPrintNum: number;
    storeMemo: string;
    statementMemo: string;
    payType: string;
    payMethod: string;
    credit: number;
    creditDays: number;
    invoiceType: string;
    invoiceName: string;
    invoiceTaxNo: string;
    invoiceAddress: string;
    invoicePhone: string;
    invoiceBank: string;
    invoiceBankAccount: string;
    invoiceContent: string;
    invoiceMemo: string;
    isOrdering: boolean;
    isMultiAccount: boolean | null;
    isComfirmOrder: boolean;
    confirmLevel: number;
    isCounter: boolean;
    isBuyOutCounter: boolean;
    isBudget: boolean;
    isStoreManager: boolean;
    py: string;
    invoiceCategory: string;
    emailForInvoice: string;
    isPublic: boolean;
    printTemplateId: number;
    onlyServiceOrder: boolean;
    onlyStatementManCheck: boolean;
    isDisable: boolean | null;
    balance: number;
    isBalance: boolean;
    balanceType: number;
    startTime: Date | null;
    endTime: Date | null;
    limitOrderByBalance: boolean | null;
    memo: string;
    winformDeliveryTemplateId: number | null;
}
