apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  selector:
    matchLabels:
      app: webapp
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        # env:
        # - name: SPRING_PROFILES_ACTIVE
        #   value: production-microservice
        image: erp-angular-webapp
        # pull image from remote server ? 
        imagePullPolicy: Never
        readinessProbe:
          httpGet:
            path: /
            port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: erp-angular-webapp

spec:
  # This defines which pods are going to be represented by this Service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  # minikube start --extra-config=apiserver.service-node-port-range=80-30000, 
  # port 80 can be used as well
  selector:
    app: webapp

  ports:
    - name: http
      port: 80
      nodePort: 80

  type: NodePort